trigger:
  branches:
    include:
    - master
mr:
  branches:
    include:
    - master

stages:
- stage:
  - job:
      name: Linux Job
      pool:
        container: mirrors.tencent.com/ci/tlinux_ci:latest
      steps:
      - taskType: bash@latest
        displayName: "Go Build"
        inputs:
          scriptType: SHELL
          content: |
            #!/bin/bash
            echo "--------------start------------"
            mkdir -p /home/baoloongmao/go/src/github.com/kahing
            ln -s `pwd` /home/baoloongmao/go/src/github.com/kahing/goofys
            cd /home/baoloongmao/go/src/github.com/kahing/goofys
            pwd
            env
            echo "--------------start------------"
            git submodule init
            git submodule update
            go build -ldflags "-X main.Version=`git rev-parse HEAD`"
      - taskType: marketBuild@latest
        displayName: Upload Artifacts
        inputs:
          atomCode: UploadArtifactory
          name: goofys.tar.gz
          version: 1.*
          data:
            input:
              filePath: ".ci.yml"
              isCustomize: false
