trigger:
  branches:
    include:
    - master
mr:
  branches:
    include:
    - master

stages:
- stage:
  - job:
      name: Linux Job
      pool:
        container: mirrors.tencent.com/ci/tlinux_ci:latest
      steps:
      - taskType: bash@latest
        displayName: "Go Build"
        inputs:
          scriptType: SHELL
          content: |
            #!/bin/bash
            go build -v .
      - taskType: marketBuild@latest
        displayName: Upload Artifacts
        inputs:
          atomCode: UploadArtifactory
          name: goofys.tar.gz
          version: 1.*
          data:
            input:
              filePath: ".ci.yml"
              isCustomize: false
